<?php


$produtos = array (
    0 => array ('nome'=>'Uma Segunda Chance','tipo'=>'livro único','preço'=>'25 reais','autor'=>'Autor(a): Colleen Hoover','genero'=>'romance','avaliacao'=>'quatro-estrelas.png','sinopse'=>'Será que todos merecem uma segunda chance? É o que mais deseja Kenna Rowan, na luta para recuperar os pedaços estilhaçados de sua antiga vida após um trágico acidente ter colocado tudo a perder. Uma segunda chance é o tão esperado novo romance de Colleen Hoover, CoHo para os íntimos, autora fenômeno de vendas, que já ultrapassou a marca de 1 milhão de exemplares vendidos no Brasil.','imagem'=>'reminders-of-him.jpg'),
    1 => array ('nome'=>'A Hipótese do Amor','tipo'=>'livro único','preço'=>'30 reais','autor'=>'Autor(a): Ali Hazelwood','genero'=>'romance','avaliacao'=>'cinco-estrelas.png','sinopse'=>'Quando um namoro de mentira entre cientistas encontra a irresistível força da atração, todas as teorias cuidadosamente calculadas sobre o amor são postas à prova. Com personagens cativantes e diálogos afiados, este livro engraçado, sexy e inteligente se tornou uma das grandes sensações do TikTok.', 'imagem'=>'love-hypothesis.jpg'),
    2 => array ('nome'=>'A Vida Invisível de Addie LaRue','tipo'=>'livro único','preço'=>'30 reais','autor'=>'Autor(a): V.E Schwab','genero'=>'fantasia/ficção','avaliacao'=>'cinco-estrelas.png','sinopse'=>'Uma vida que ninguém lembra. Um livro que ninguém esquece. Em A vida invisível de Addie LaRue, o aguardado best-seller de V.E. Schwab, conheça Addie e se perca em sua vida invisível ― porém memorável.','imagem'=>'addie-larue.jpg'),
    3 => array ('nome'=>'Corte de Névoa e Fúria (ACOTAR livro 2)','tipo'=>'livro único','preço'=>'35 reais','autor'=>'Autor(a): Sarah J.Maas','genero'=>'fantasia/ficção','avaliacao'=>'cinco-estrelas.png','sinopse'=>'Em Corte de névoa e fúria, segundo volume da série best-seller no Brasil e no mundo, seguimos a saga de Feyre Archeron, que morreu Sob a Montanha. Uma edição especial de colecionador, com capa dura, pintura trilateral e um projeto gráfico inédito e exclusivo, em comemoração da venda de 1 milhão de exemplares de Sarah J. Maas no Brasil.', 'imagem'=>'acomaf.jpg'),
    4 => array ('nome'=>'Amor e Gelato','tipo'=>'livro único','preço'=>'20 reais','autor'=>'Autor(a): Jenna Evans Welch','genero'=>'romance','avaliacao'=>'quatro-estrelas.png','sinopse'=>'Uma trajetória que fará Lina descobrir o amor, a si mesma e também aprender a lidar com a perda. Amor & gelato é uma deliciosa viagem pelos mais românticos pontos turísticos italianos, com direito a tudo de mais intenso que o lugar tem a oferecer: desde paixões até corações partidos.','imagem'=>'amor-gelato.jpg'),
    5 => array ('nome'=>'Amores Verdadeiros','tipo'=>'livro único','preço'=>'20 reais','autor'=>'Autor(a): Taylor Jenkins Reid','genero'=>'romance','avaliacao'=>'quatro-estrelas.png','sinopse'=>'Emma Blair casou com seu namorado do colegial, Jesse, quando tinha vinte anos. Juntos, eles construíram uma vida diferente das expectativas de seus pais e das pessoas de sua cidade natal, Massachusetts. Sem perder nenhuma oportunidade de viver novas aventuras, eles viajam o mundo todo, curtindo a vida ao máximo. Mas, em vez do tradicional "e viveram felizes para sempre", uma tragédia separa os dois, no dia do seu aniversário de um ano de casamento. O helicóptero com o qual Jesse sobrevoava o Pacífico desaparece e, simples assim, o amor da vida de Emma se vai para sempre. Emma volta para sua cidade natal em uma tentativa de reconstruir a vida e, depois de anos de luto, reencontra um velho amigo, Sam, que lhe mostra ser, sim, possível se apaixonar novamente. E quando os dois ficam noivos? Emma sente que a vida lhe deu uma segunda chance de ser feliz. Pelo menos é o que parece ― até que Jesse é encontrado. Ele está vivo e tentou voltar para casa, para Emma, todos esses anos que passou desaparecido. Agora, com um marido e um noivo, Emma precisa descobrir quem ela é e o que quer, enquanto tenta proteger todos que ama','imagem'=>'amores-verdadeiros.jpg'),
    6 => array ('nome'=>'Casa de Terra e Sangue (livro 1)','tipo'=>'livro único','preço'=>'35 reais','autor'=>'Autor(a): Sarah J.Maas','genero'=>'fantasia/ficção','avaliacao'=>'cinco-estrelas.png','sinopse'=>'A autora #1 do New York Times Sarah J. Maas lança sua nova série Cidade da Lua Crescente, agora com tradução revista. Neste primeiro volume, Casa de terra e sangue, conhecemos a história da semifeérica Bryce Quinlan, que busca vingança em um mundo de fantasia contemporâneo repleto de magia, perigo e romance abrasador.','imagem'=>'crecent-city.jpg'),
    7 => array ('nome'=>'Estilhaça-me (livro 1)','tipo'=>'livro único','preço'=>'20 reais','autor'=>'Autor(a): Tahere Mafi','genero'=>'fantasia/ficção','avaliacao'=>'quatro-estrelas.png','sinopse'=>'No eletrizante primeiro volume da série Estilhaça-me, Tahereh Mafi apresenta um mundo distópico hipnotizante, uma emocionante história de super-heróis e uma heroína inesquecível.','imagem'=>'estilhaca-me.jpg'),
    8 => array ('nome'=>'A Garota do Lago','tipo'=>'livro único','preço'=>'15 reais','autor'=>'Autor(a): Charlie Donlea','genero'=>'suspense','avaliacao'=>'quatro-estrelas.png','sinopse'=>'Summit Lake, uma pequena cidade entre montanhas, é esse tipo de lugar, bucólico e com encantadoras casas dispostas à beira de um longo trecho de água intocada.Duas semanas atrás, a estudante de direito Becca Eckersley foi brutalmente assassinada em uma dessas casas. Filha de um poderoso advogado, Becca estava no auge de sua vida. Atraída instintivamente pela notícia, a repórter Kelsey Castle vai até a cidade para investigar o caso. ...E LOGO SE ESTABELECE UMA CONEXÃO ÍNTIMA QUANDO UM VIVO CAMINHA NAS MESMAS PEGADAS DOS MORTOS...E enquanto descobre sobre as amizades de Becca, sua vida amorosa e os segredos que ela guardava, a repórter fica cada vez mais convencida de que a verdade sobre o que aconteceu com Becca pode ser a chave para superar as marcas sombrias de seu próprio passado.','imagem'=>'garota-do-lago.jpg'),
    9 => array ('nome'=>'Harry Potter e a Pedra Filosofal (livro 1)','tipo'=>'livro único','preço'=>'20 reais','autor'=>'Autor(a): J.K Rowlling','genero'=>'fantasia/ficção','avaliacao'=>'cinco-estrelas.png','sinopse'=>'Harry Potter é um garoto cujos pais, feiticeiros, foram assassinados por um poderosíssimo bruxo quando ele ainda era um bebê. Ele foi levado, então, para a casa dos tios que nada tinham a ver com o sobrenatural. Pelo contrário. Até os 10 anos, Harry foi uma espécie de gata borralheira: maltratado pelos tios, herdava roupas velhas do primo gorducho, tinha óculos remendados e era tratado como um estorvo. No dia de seu aniversário de 11 anos, entretanto, ele parece deslizar por um buraco sem fundo, como o de Alice no país das maravilhas, que o conduz a um mundo mágico. Descobre sua verdadeira história e seu destino: ser um aprendiz de feiticeiro até o dia em que terá que enfrentar a pior força do mal, o homem que assassinou seus pais. O menino de olhos verde, magricela e desengonçado, tão habituado à rejeição, descobre, também, que é um herói no universo dos magos. Potter fica sabendo que é a única pessoa a ter sobrevivido a um ataque do tal bruxo do mal e essa é a causa da marca em forma de raio que ele carrega na testa. Ele não é um garoto qualquer, ele sequer é um feiticeiro qualquer ele é Harry Potter, símbolo de poder, resistência e um líder natural entre os sobrenaturais. A fábula, recheada de fantasmas, paredes que falam, caldeirões, sapos, unicórnios, dragões e gigantes, não é, entretanto, apenas um passatempo.','imagem'=>'harry-potter.jpg'),
    10 => array ('nome'=>'Mentirosos','tipo'=>'livro único','preço'=>'20 reais','autor'=>'Autor(a): E. Lockhart','genero'=>'suspense','avaliacao'=>'quatro-estrelas.png','sinopse'=>'Um suspense moderno e sofisticado, Mentirosos é impossível de largar até que todos seus mistérios sejam desvendados. A prosa lírica e o estilo seco e denso farão você mergulhar de cabeça no mundo dos Sinclair, uma família rica e tradicional, e nas crescentes angústias da protagonista Cadence - para então vir à tona completamente impactado.','imagem'=>'mentirosos.jpg'),
    11 => array ('nome'=>'Mil Beijos de Garoto','tipo'=>'livro único','preço'=>'25 reais','autor'=>'Autor(a): Tillie Cole','genero'=>'romance','avaliacao'=>'quatro-estrelas.png','sinopse'=>'Quando, aos dezessete anos, Rune Kristiansen retorna da Noruega para o lugar onde passou a infância, a cidade americana de Blossom Grove, na Geórgia , ele só tem uma coisa em mente: reencontrar Poppy Litchfield, a garota que era sua cara-metade e que tinha prometido esperar fielmente por seu retorno. E ele quer descobrir por que, nos dois anos em que esteve fora, ela o deletou de sua vida sem dar nenhuma explicação.','imagem'=>'mil-beijos-de-garoto.jpg'),
    12 => array ('nome'=>'O Príncipe Cruel (livro 1)','tipo'=>'livro único','preço'=>'25 reais','autor'=>'Autor(a): Holly Black','genero'=>'fantasia/ficção','avaliacao'=>'cinco-estrelas.png','sinopse'=>'O prínicipe cruel é o primeiro volume da série best-seller O Povo do Ar.','imagem'=>'principe-cruel.jpg'),
    13 => array ('nome'=>'Teto Para Dois','tipo'=>'livro único','preço'=>'25 reais','autor'=>'Autor(a): Beth Oleary','genero'=>'romance','avaliacao'=>'quatro-estrelas.png','sinopse'=>'Eles dividem um apartamento com uma cama só. Ele dorme de dia, ela, à noite. Os dois nunca se encontraram, mas estão prestes a descobrir que, para se sentir em casa, às vezes é preciso jogar as regras pela janela.','imagem'=>'teto-para-dois.jpg'),
    14 => array ('nome'=>'Trono de Vidro (livro 1)','tipo'=>'livro único','preço'=>'30 reais','autor'=>'Autor(a): Sarah J.Maas','genero'=>'fantasia/ficção','avaliacao'=>'cinco-estrelas.png','sinopse'=>'A magia há muito abandonou Adarlan.  Um perverso rei governa, punindo impiedosamente as minorias rebeldes','imagem'=>'trono-de-vidro.jpg'),
    15 => array ('nome'=>'Box Trilogia Tons de Magia (com brindes)','tipo'=>'box','preço'=>'70 reais','autor'=>'Autor(a): V.E Schwab','genero'=>'fantasia/ficção','avaliacao'=>'cinco-estrelas.png','sinopse'=>'Um universo de aventuras audaciosas, poder e múltiplas cidades de Londres. Acompanhe Kell e Lila em uma jornada épica de tirar o fôlego.','imagem'=>'box-tons-de-magia.jpg'),
    16 => array ('nome'=>'Box Trilogia O Povo do Ar','tipo'=>'box','preço'=>'75 reais','autor'=>'Autor(a): Holly Black','genero'=>'fantasia/ficção','avaliacao'=>'cinco-estrelas.png','sinopse'=>'Os três volumes da série O povo do ar e o spin-off reunidos pela primeira vez em um box com conteúdos especiais. O conto inédito “As irmãs perdidas”, o mapa de Elfhame atualizado no verso das capas, uma capa nova para O canto mais escuro da floresta, e brindes como uma cinta em formato de coroa de papel, marcadores, pôster exclusivo com uma fan art da Arda Arts e uma flâmula.','imagem'=>'box-povo-do-ar.jpg'),
    17 => array ('nome'=>'Os Sete Maridos de Evelyn Hugo','tipo'=>'livro único','preço'=>'25 reais','autor'=>'Autor(a): Taylor Jenkins Reid','genero'=>'romance','avaliacao'=>'cinco-estrelas.png','sinopse'=>'Com todo o esplendor que só a Hollywood do século passado pode oferecer, esta é uma narrativa inesquecível sobre os sacrifícios que fazemos por amor, o perigo dos segredos e o preço da fama.','imagem'=>'evelyn-hugo.jpg'),
    18 => array ('nome'=>'Verity','tipo'=>'livro único','preço'=>'30 reais','autor'=>'Autor(a): Colleen Hoveer','genero'=>'suspense','avaliacao'=>'quatro-estrelas.png','sinopse'=>'Finalista do prêmio Goodreads como melhor romance de 2019. Um casal apaixonado. Uma intrusa. Três mentes doentias.','imagem'=>'verity.jpg'),
    19 => array ('nome'=>'Os Cinco Porquinhos','tipo'=>'livro único','preço'=>'15 reais','autor'=>'Autor(a): Agatha Christie','genero'=>'suspense','avaliacao'=>'quatro-estrelas.png','sinopse'=>'Em um de seus mais intrigantes casos, Hercule Poirot enfrentará um opositor que desafiará sua inteligência e sagacidade: o tempo. Procurado pela bela jovem Carla Lemarchant, Poirot é contratado para investigar um terrível crime que acontecera dezesseis anos antes, e que envolveu os pais da moça. Caroline Crale foi condenada à prisão perpétua e submetida a trabalhos forçados pelo assassinato do marido, o famoso pintor Amyas Crale. Mas, antes de morrer na prisão, enviara à filha, então criança, uma carta afirmando sua inocência. Tantos anos depois, não há mais evidências a serem colhidas. As pistas e provas deverão ser tomadas apenas na análise psicológica das testemunhas, e, para tanto, Poirot contará com sua capacidade de compreensão profunda do espírito humano para desvendar esse mistério. Nas entrevistas que Poirot faz com as cinco testemunhas do crime se revelam seus caracteres e intenções, e fortes sentimentos vêm à tona: angústia, inveja, amor, desejo, cobiça, ciúme. Quem, além de Caroline, teria motivos para assassinar Amyas? O que se esconde por trás dos relatos das testemunhas? O que de fato aconteceu na propriedade dos Crale naquele fatídico dia? Nada leva a crer que alguma daquelas pessoas possa ter assassinado Amyas Carle, impulsionando o leitor a prestar muita atenção aos detalhes dos relatos, a fim de acompanhar o aguçado raciocínio de Poirot nesta trama cheia de sutilezas, e que culmina em uma surpreendente revelação do assassino e dos curiosos motivos do assassinato.','imagem'=>'cinco-porquinhos.jpg'),
    20 => array ('nome'=>'Box Agatha Christie','tipo'=>'box','preço'=>'45 reais','autor'=>'Autor(a): Agatha Christie','genero'=>'suspense','avaliacao'=>'cinco-estrelas.png','sinopse'=>'Livro 1 - Hora zero Livro 2 - O Natal de Poirot Livro 3 - Treze à mesa','imagem'=>'box-agatha-christie.jpg'),
    21 => array ('nome'=>'Box Trilogia Verão','tipo'=>'box','preço'=>'55 reais','autor'=>'Autor(a): Jenny Han','genero'=>'romance','avaliacao'=>'quatro-estrelas.png','sinopse'=>'Na trilogia Verão, acompanhamos Belly dos 15 aos 24 anos. Em meio a descobertas e mudanças, ela se apaixona, se envolve em um triângulo amoroso, entra na universidade e descobre que amadurecer também significa tomar decisões difíceis. Primeiros romances jovens de Jenny Han, os três livros são agora relançados pela Intrínseca, com novas capas e traduções inéditas.','imagem'=>'verao.jpg'),
    22 => array ('nome'=>'Era uma Vez um Coração Partido','tipo'=>'livro único','preço'=>'30 reais','autor'=>'Autor(a): Stephanie Garber','genero'=>'fantasia/ficção','avaliacao'=>'cinco-estrelas.png','sinopse'=>'A nova série de Stephanie Garber, aclamada autora da trilogia Caraval, nos levará para um universo de amor e maldições, revelando até onde as pessoas são capazes de ir por um final feliz.','imagem'=>'once-upon-a-broken-heart.jpg'),
    23 => array ('nome'=>'Corte de Espinhos e Rosas (ACOTAR livro 1)','tipo'=>'livro único','preço'=>'20 reais','autor'=>'Autor(a): Sarah J.Maas','genero'=>'fantasia/ficção','avaliacao'=>'quatro-estrelas.png','sinopse'=>'Ela roubou uma vida. Agora deve pagar com o coração. Corte de espinhos e rosas é primeiro volume da série best-seller, da mesma autora da saga Trono de vidro.','imagem'=>'acotar.jpg'),
    24 => array ('nome'=>'Orgulho e Preconceito','tipo'=>'livro único','preço'=>'15 reais','autor'=>'Autor(a): Jane Austen','genero'=>'romance','avaliacao'=>'cinco-estrelas.png','sinopse'=>'Orgulho e preconceito é o livro mais famoso de Jane Austen e possui uma série de personagens inesquecíveis e um enredo memorável. Austen nos apresenta Elizabeth Bennet como heroína irresistível e seu pretendente aristocrático, o sr. Darcy. Nesse livro, aspectos diferentes são abordados: orgulho encontra preconceito, ascendência social confronta desprezo social, equívocos e julgamentos antecipados conduzem alguns personagens ao sofrimento e ao escândalo.','imagem'=>'orgulho-e-preconceito.jpg'),
    25 => array ('nome'=>'Box Hopeless','tipo'=>'box','preço'=>'50 reais','autor'=>'Autor(a): Colleen Hoveer','genero'=>'romance','avaliacao'=>'cinco-estrelas.png','sinopse'=>'Da autora dos best-sellers É assim que acaba e Verity, conheça Sky, Holder, Six e Daniel em um kit que reúne pela primeira vez as histórias dos personagens da série Hopeless, em novas edições com capas inéditas da artista Carmell Louize e marcadores temáticos (Um Caso Perdido, Sem Esperança e Em Busca de Cinderela).','imagem'=>'hopeless.jpg'),
    26 => array ('nome'=>'Clube do Livro dos Homens','tipo'=>'livro único','preço'=>'25 reais','autor'=>'Autor(a): Lyssa Kay Adams','genero'=>'romance','avaliacao'=>'cinco-estrelas.png','sinopse'=>'Gavin Scott é um astro do beisebol, devotado ao esporte. No auge de sua carreira, ele descobre um segredo humilhante: a esposa, Thea, sempre fingiu ter prazer na cama. Magoado, Gavin para de falar com ela e acaba piorando o relacionamento, que já vinha se deteriorando. Quando Thea pede o divórcio, ele percebe que o orgulho e o medo podem fazê-lo perder tudo. Desesperado, Gavin encontra ajuda onde menos espera: um clube secreto de romances, composto por alguns dos seus colegas de time. Para salvar seu casamento, eles recorrem à leitura de uma sensual trama de época, Cortejando a condessa. Só que vai ser preciso muito mais do que palavras floreadas e gestos grandiosos para que Gavin recupere a confiança da esposa.','imagem'=>'bromance-bookclub.jpg'),
    27 => array ('nome'=>'Box Percy Jackson (5 livros)','tipo'=>'box','preço'=>'80 reais','autor'=>'Autor(a): Rick Riordan','genero'=>'fantasia/ficção','avaliacao'=>'cinco-estrelas.png','sinopse'=>'Combinando mitologia grega e muita aventura, a saga do menino Percy Jackson, que aos 12 anos descobre que é um semideus, filho de Poseidon, tornou-se um fenômeno mundial.','imagem'=>'percy-jackson.jpg'),
    28 => array ('nome'=>'Box Harry Potter (7 livros)','tipo'=>'box','preço'=>'95 reais','autor'=>'Autor(a): J.K Rowlling','genero'=>'fantasia/ficção','avaliacao'=>'cinco-estrelas.png','sinopse'=>'Em sete livros que se tornaram o maior fenômeno editorial de todos os tempos, com mais de 450 milhões de exemplares vendidos e traduções em 78 idiomas, Harry Potter não é exposto apenas a batalhas e feitiços. Ele precisa superar traições, surpresas e, sobretudo, aprender a lidar com os próprios sentimentos. O amor, a amizade e claro, uma boa dose de magia e imaginação, são os elementos-chave para da maior saga bruxa de todos os tempos. Box Harry Potter – Série Completa: perfeito para todos que cresceram acompanhando a saga do jovem bruxo e para as novas gerações de fãs que anseiam por conhecê-la!','imagem'=>'box-harry-potter.jpg'),
    29 => array ('nome'=>'Box Heróis do Olimpo (5 livros)','tipo'=>'box','preço'=>'75 reais','autor'=>'Autor(a): Rick Riordan','genero'=>'fantasia/ficção','avaliacao'=>'quatro-estrelas.png','sinopse'=>'Depois de salvar o Olimpo do maligno titã Cronos, Percy Jackson e seus amigos se deparam com um novo inimigo e com uma nova e aterrorizante profecia. Gaia, a Mãe Terra, está despertando e pretende destruir os deuses, semideuses e quem mais estiver no caminho. Para impedi-la, semideuses romanos e gregos precisarão se unir para combatê-la.','imagem'=>'herois-do-olimpo.jpg'),
    30 => array ('nome'=>'Percy Jackson e o Ladrão de Raios (Percy Jackson livro 1)','tipo'=>'livro único','preço'=>'15 reais','autor'=>'Autor(a): Rick Riordan','genero'=>'fantasia/ficção','avaliacao'=>'cinco-estrelas.png','sinopse'=>'O autor conjuga lendas da mitologia grega com aventuras no século XXI. Nelas, os deuses do Olimpo continuam vivos, ainda se apaixonam por mortais e geram filhos metade deuses, metade humanos, como os heróis da Grécia antiga. Marcados pelo destino, eles dificilmente passam da adolescência. Poucos conseguem descobrir sua identidade.O garoto-problema Percy Jackson é um deles. Tem experiências estranhas em que deuses e monstros mitológicos parecem saltar das páginas dos livros direto para a sua vida. Pior que isso: algumas dessas criaturas estão bastante irritadas. Um artefato precioso foi roubado do Monte Olimpo e Percy é o principal suspeito. Para restaurar a paz, ele e seus amigos – jovens heróis modernos – terão de fazer mais do que capturar o verdadeiro ladrão: precisam elucidar uma traição mais ameaçadora que fúria dos deuses.','imagem'=>'percy-jackson-um.jpg'),


);

?>
